//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snake_game
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_All_Players
    {
        public string PlayerName { get; set; }
        public Nullable<int> PlayerScore { get; set; }
    }
}
